# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# This values file is used to support the 3pa parent chart
# deployment. Check that chart to modify these values.

replicas: 1

appName: unzip-and-ingest

global:
  useTls: true
  useTLSClientAuth: false
  sslCertSecretName: ssl-certs
  authSslCertSecretName: pki-ssl-certs
  dockerRepository: nexus-docker-proxy.3pa.maxar.com
  hostname: omar.3pa.maxar.com

  createIngress: true

  imagePullSecret:
    registry: nexus-docker-proxy.3pa.maxar.com
    username: radiantcibot
    password: lhLvXspFyX9wraf6jB1I

  createImagePullSecret: true
  useImagePullSecret: true

  createHpa: true
  createPVs: true
  useSpringConfigServer: false

  volumes:
    maxar-blacksky-data:
      type: nfs
      nfsServer: 10.100.40.114
      nfsMountPoint: /3pa-blacksky
      accessModes:
        - ReadWriteMany
      size: 500Gi
      mountPath: /3pa-blacksky

    maxar-skysat-data:
      type: nfs
      nfsServer: 10.100.40.114
      nfsMountPoint: /3pa-skysat
      accessModes:
        - ReadWriteMany
      size: 500Gi
      mountPath: /3pa-skysat

image:
  name: unzip-and-ingest
  tag: 1.1.0
  pullPolicy: IfNotPresent

internalPort: 8080
externalPort: 8080

readinessProbe:
  path: /health
  port: 8080
  initialDelaySeconds: 5
  timeoutSeconds: 3
livenessProbe:
  path: /health
  port: 8080
  initialDelaySeconds: 5
  timeoutSeconds: 3
  failureThreshold: 10


baseUrl: http://omar-stager-app:8080

wfsBaseUrl: https://omar-3pa.ossim.io/
wfsPostPrefix: "omar-wfs/wfs/getFeature?maxFeatures=1&outputFormat=JSON&propertyName=filename&resultType=results&request=GetFeature&service=WFS&typeName=omar:raster_entry&filter=filename=%27"
wfsFilenamePrefix: empty

sqsQueueArn: "arn:aws:sqs:us-east-1:576113035271:gegd-processed-images"
ingestAlertQueueArn: "arn:aws:sqs:us-east-1:576113035271:gegd-ingest-alert"

volumeNames:
  - maxar-blacksky-data
  - maxar-skysat-data