# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

appName: unzip-and-ingest

global:
  dockerRepository: nexus-docker-public-hosted.ossim.io

image:
  name: unzip-and-ingest
  tag: latest
  pullPolicy: Always


nfs:
  server: o2-nfs.private.ossim.io

storage: 16G

volumeNameBlackSky: maxar-blacksky-data
volumeMountPathBlackSky: /maxar-blacksky-data

volumeNameSkySat: maxar-skysat-data
volumeMountPathSkySat: /maxar-skysat-data

configmap:
  baseUrl: https://omar-3pa-dev.ossim.io
  mountBuckets:
    - maxar-blacksky-data
    - maxar-skysat-data