apiVersion: apps/v1
kind: Deployment
metadata:
  name: "gegd-processing"
spec:
  selector:
    matchLabels:
      app: "gegd-processing"
  template:
    metadata:
      labels:
        app: "gegd-processing"
    spec:
      containers:
        - name: "gegd-processing"
          image: "nexus-docker-public-hosted.ossim.io/gegd-processing"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
          volumeMounts:
            - mountPath: /maxar-blacksky-data
              name: blacksky-data
      volumes:
        - name: blacksky-data
          persistentVolumeClaim:
            claimName: gegd-processing-blacksky-data-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gegd-processing
  labels:
    app: gegd-processing
data:
  application.yaml: |-
    app:
      post:
        url:
          prefix: 'https://omar-3pa-dev.ossim.io/omar-stager/dataManager/addRaster?filename='
          suffix: '&background=true&buildThumbnails=true&buildOverviews=true&buildHistograms=true&buildHistogramsWithR0=true&useFastHistogramStaging=false&overviewType=ossim_tiff_box&overviewCompressionType=NONE&thumbnailSize=512&thumbnailType=jpeg&thumbnailStretchType=auto-minmax'
      mounts:
        - bucket: maxar-blacksky-data
          ingestDirectory: ingest
          archiveDirectory: archive
          unzipDirectory: unzipped
        - bucket: maxar-skysat-data
          ingestDirectory: ingest
          archiveDirectory: archive
          unzipDirectory: unzipped
      parsing:
        dateKeys:
          - acquisitionDate
          - acquired
        omdKeyMapList:
          - key: mission_id
            oldKeys:
              - provider
              - sensorName
            values:
              - oldValue: gegd
                newValue: SkySat
              - oldValue: skysat
                newValue: SkySat
              - oldValue: Global-1
                newValue: BlackSky
              - oldValue: Global-2
                newValue: BlackSky
              - oldValue: Global-3
                newValue: BlackSky
              - oldValue: Global-4
                newValue: BlackSky
              - oldValue: Global-5
                newValue: BlackSky
              - oldValue: Global-6
                newValue: BlackSky
              - oldValue: Global-7
                newValue: BlackSky
              - oldValue: Global-8
                newValue: BlackSky
              - oldValue: Global-9
                newValue: BlackSky
              - oldValue: Global-10
                newValue: BlackSky
      fileExtensions:
        - ntf
        - ntif